export { Editor } from "./lib/editor/Editor";
export {
  StateNode,
  type TLStateNodeConstructor,
} from "./lib/editor/tools/StateNode";
export { type TLContent } from "./lib/editor/types/clipboard-types";
export {
  type TLEventMap,
  type TLEventMapHandler,
} from "./lib/editor/types/emit-types";
export {
  EVENT_NAME_MAP,
  type TLBaseEventInfo,
  type TLCancelEvent,
  type TLCancelEventInfo,
  type TLClickEvent,
  type TLClickEventInfo,
  type TLCLickEventName,
  type TLCompleteEvent,
  type TLCompleteEventInfo,
  type TLEnterEventHandler,
  type TLEventHandlers,
  type TLEventInfo,
  type TLEventName,
  type TLExitEventHandler,
  type TLInterruptEvent,
  type TLInterruptEventInfo,
  type TLKeyboardEvent,
  type TLKeyboardEventInfo,
  type TLKeyboardEventName,
  type TLPinchEvent,
  type TLPinchEventInfo,
  type TLPinchEventName,
  type TLPointerEvent,
  type TLPointerEventInfo,
  type TLPointerEventName,
  type TLPointerEventTarget,
  type TLTickEvent,
  type TLTickEventInfo,
  type TLWheelEvent,
  type TLWheelEventInfo,
  type UiEvent,
  type UiEventType,
} from "./lib/editor/types/event-types";
export {
  Box,
  ROTATE_CORNER_TO_SELECTION_CORNER,
  rotateSelectionHandle,
  type BoxLike,
  type RotateCorner,
  type SelectionCorner,
  type SelectionEdge,
  type SelectionHandle,
} from "./lib/primitives/Box";

export {
  angleDistance,
  approximately,
  areAnglesCompatible,
  average,
  canonicalizeRotation,
  centerOfCircleFromThreePoints,
  clamp,
  clampRadians,
  clockwiseAngleDist,
  counterClockwiseAngleDist,
  degreesToRadians,
  getArcMeasure,
  getPointInArcT,
  getPointOnCircle,
  getPointsOnArc,
  getPolygonVertices,
  HALF_PI,
  isSafeFloat,
  perimeterOfEllipse,
  PI,
  PI2,
  pointInPolygon,
  precise,
  radiansToDegrees,
  rangeIntersection,
  shortAngleDist,
  SIN,
  snapAngle,
  toDomPrecision,
  toFixed,
  toPrecision,
} from "./lib/primitives/utils";

export { Mat, type MatLike, type MatModel } from "./lib/primitives/Mat";
export { Vec, type VecLike } from "./lib/primitives/Vec";
export {
  intersectCircleCircle,
  intersectCirclePolygon,
  intersectCirclePolyline,
  intersectLineSegmentCircle,
  intersectLineSegmentLineSegment,
  intersectLineSegmentPolygon,
  intersectLineSegmentPolyline,
  intersectPolygonBounds,
  intersectPolygonPolygon,
  linesIntersect,
  polygonIntersectsPolyline,
  polygonsIntersect,
} from "./lib/primitives/intersect";
